Polishing of wflow example notebook
eWaterCycle/ewatercycle pull request #170
Opened 2021-07-12 12:18 UTC by sverhoeven

2021-07-13 10:03 UTC, Peter9192 requested changes
Nice work so far! Few small comments, also see nbreview.

By the way: the azure item says pcrglob will become the example API notebooks.

2021-07-13 10:03 UTC, Peter9192 commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
This would always raise for a new user, right? In light of #159, should we revert to using a sif file?

2021-07-13 10:03 UTC, Peter9192 commented on ewatercycle/models/wflow.py
> +        if self.version == "2020.1.1":
This block is very specific. I think it's okay for now, but eventually we should come up with something better.

2021-07-13 10:03 UTC, Peter9192 commented on tests/models/test_wflow.py
> +        "Requested point was lon: 5.2, lat: 46.8;" " closest grid point is 5.00, 47.00."
```suggestion
        "Requested point was lon: 5.2, lat: 46.8; closest grid point is 5.00, 47.00."
```

2021-07-14 07:50 UTC, sverhoeven commented
Thanks for reviewing, I added most of your suggestions and replied to them. Can you have another look?

2021-07-14 10:10 UTC, Peter9192 commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
@sverhoeven what do you think about this?

2021-07-15 08:21 UTC, sverhoeven commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
Yep, having the image download within 15 seconds is very unlikely. That is why I wrote https://ewatercycle.readthedocs.io/en/latest/system_setup.html#model-container-images , so with properly setup system your should not get this exception. 

I suggest we change to sif file in a separate PR that works on #159.

2021-07-15 11:02 UTC, Peter9192 commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
but does `singularity exec docker://ewatercycle/wflow-grpc4bmi:2020.1.1 run-bmi-server -h` make the image available for all users?

2021-07-15 12:06 UTC, sverhoeven commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
Nope it doesnt, its stored in ~/.singularity/cache, that is the con described in #159

2021-07-16 07:19 UTC, Peter9192 commented on ewatercycle/models/wflow.py
>                      "the singularity image was missing."
Okay let's move it to another PR, but I think this should still be changed.

2021-07-16 07:19 UTC, Peter9192 approved these changes

2021-07-16 07:20 UTC, merged