Change units caravan forcing
eWaterCycle/ewatercycle pull request #417
Opened 2024-05-29 06:26 UTC by RolfHut

I have added a few lines to change the units of the caravan forcings to be in line with the NETCDF CF conventions and compatible with the output of the Makking and Generic Lumped forcings.

2024-05-29 07:22 UTC, BSchilperoort requested changes
Having the Caravan forcing homogenized with the other forcings is a good idea. Perhaps we should add some info on this to the documentation so it is easier for people to refer to that (e.g. a table with units and some references).

It's generally not best practice to change things like this "silently" on a non-major release, but I assume that the only other user of the Caravan forcing right now is @Daafip, so he will be aware of the changes.

Can you also update the changelog and perhaps add unit test?

2024-05-29 07:22 UTC, BSchilperoort commented on src/ewatercycle/_forcings/caravan.py
> +            #convert units to Kelvin for compatiabillity with NetCDF-CF conventions
```suggestion
            #convert units to Kelvin for compatibility with CMOR MIP table units
```
The netCDF-CF convention just specifies you need to use units from [UDUNITS-2](https://docs.unidata.ucar.edu/udunits). degC is a valid unit there.

However, the units are standardized from the CMIP comparisons in so called "MIP tables". For example, the [CMIP6_day table](https://github.com/PCMDI/cmip6-cmor-tables/blob/main/Tables/CMIP6_day.json).

2024-05-29 07:22 UTC, BSchilperoort commented on src/ewatercycle/_forcings/caravan.py
> +                ds_basin[temp].attrs["unit"] = "°K"
```suggestion
                ds_basin[temp].attrs["unit"] = "K"
```

2024-05-29 07:22 UTC, BSchilperoort commented on src/ewatercycle/_forcings/caravan.py
> +                ds_basin[var].values = ds_basin[temp].values / (86400) #NOTE THAT THIS CONVERSION ASSUMES DAILY DATA
"All time series data except streamflow are aggregated (daily and spatially over basins)", Kratzert 2023.

And all these other time series data is merged with the streamflow on the same time dimension in the netCDF files we host on 4TU. So I think it's safe to hard code the conversion here.
```suggestion
                ds_basin[var].values = ds_basin[temp].values / (86400)  # mm/day --> kg m-2 s-1
```

2024-05-29 09:03 UTC, Daafip commented
> I assume that the only other user of the Caravan forcing right now is @Daafip, so he will be aware of the change
 Yup, for my thesis actually using the original camels dataset still as Caravan is fully Era5 based.

2024-05-29 09:04 UTC, Daafip approved these changes

2024-06-03 06:08 UTC, BSchilperoort approved these changes
I applied the fixes we discussed last week. Tests (should) pass now.

I'll merge this into #420 to have it included in the latest release.

2024-06-03 06:09 UTC, merged